<!-- Top Navigation Bar -->
            <div class="container">

                <!-- Only visible on smartphones, menu toggle -->
                <ul class="nav navbar-nav">
                    <li class="nav-toggle"><a href="javascript:void(0);" title=""><i class="icon-reorder"></i></a></li>
                </ul>

                <!-- Logo -->
                <a class="navbar-brand" href="index.html">
                    <img src="<?php echo ASSETS_URL; ?>assets/img/logo.png" alt="logo" />
<!--                    <strong>ME</strong>LON-->
                </a>
                <!-- /logo -->

                <!-- Sidebar Toggler -->
                <a href="#" class="toggle-sidebar bs-tooltip" data-placement="bottom" data-original-title="Toggle navigation">
                    <i class="icon-reorder"></i>
                </a>
                <!-- /Sidebar Toggler -->

                <!-- Top Left Menu -->
                <?php include_once ("header/navigator.phtml"); ?>
                <!-- /Top Left Menu -->

                <!-- Top Right Menu -->
                <?php include_once ("header/navigator-right.phtml"); ?>
                <!-- /Top Right Menu -->
            </div>
            <!-- /top navigation bar -->

            <!--=== Project Switcher ===-->
            <div id="project-switcher" class="container project-switcher">
                <?php include_once("header/project-navigator.phtml"); ?>
            </div> <!-- /#project-switcher -->