<div id="scrollbar">
    <div class="handle"></div>
</div>

<div id="frame">
    <ul class="project-list">
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-desktop"></i></span>
                <span class="title">Lorem ipsum dolor</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-compass"></i></span>
                <span class="title">Dolor sit invidunt</span>
            </a>
        </li>
        <li class="current">
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-male"></i></span>
                <span class="title">Consetetur sadipscing elitr</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-thumbs-up"></i></span>
                <span class="title">Sed diam nonumy</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-female"></i></span>
                <span class="title">At vero eos et</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-beaker"></i></span>
                <span class="title">Sed diam voluptua</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-desktop"></i></span>
                <span class="title">Lorem ipsum dolor</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-compass"></i></span>
                <span class="title">Dolor sit invidunt</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-male"></i></span>
                <span class="title">Consetetur sadipscing elitr</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-thumbs-up"></i></span>
                <span class="title">Sed diam nonumy</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-female"></i></span>
                <span class="title">At vero eos et</span>
            </a>
        </li>
        <li>
            <a href="javascript:void(0);">
                <span class="image"><i class="icon-beaker"></i></span>
                <span class="title">Sed diam voluptua</span>
            </a>
        </li>
    </ul>
</div> <!-- /#frame -->