<ul class="nav navbar-nav navbar-right">
    <!-- User Login Dropdown -->
    <li class="dropdown user">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon-male"></i>
            <span class="username">John Doe</span>
            <i class="icon-caret-down small"></i>
        </a>
        <ul class="dropdown-menu">
            <li><a href="#"><i class="icon-key"></i> Log Out</a></li>
        </ul>
    </li>
    <!-- /user login dropdown -->
</ul>