<div class="row">
    <!--=== Example Box ===-->
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i> Example Box</h4>
            </div>
            <div class="widget-content">
                <p>Lorem Ipsum.</p>
            </div>
        </div>
    </div> <!-- /.col-md-12 -->
    <!-- /Example Box -->
</div> <!-- /.row -->
<!-- /Page Content -->